version: '3'

services:
  db:
    container_name: nestjs-microservice-mongo
    image: mongo
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - nestjs-microservice-mongo:/data/db
  postgres:
    container_name: nestjs-microservice-postgres
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - nestjs-microservice-postgres:/data/postgres
    restart: unless-stopped
    networks:
      - postgres-network
  redis:
    container_name: nestjs-microservice-redis
    image: 'redis:alpine'
    volumes:
      - nestjs-microservice-redis:/data
    ports:
      - 6379:6379
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

volumes:
  nestjs-microservice-mongo:
  nestjs-microservice-postgres:
  nestjs-microservice-redis:
networks: 
  postgres-network:
    driver: bridge