name: Release

on: 
  push: 

jobs: 
  release:
    runs-on: "ubuntu-latest"
    steps: 
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2 
        with: 
          node-version: 16
      - run: npm i @nestjs/cli
      - run: npm run build
      - run: npx semantic-release